# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 424ef283d76eabcf30c1c79517cb0dd284e303c86238e520d3d3866cc0e437df32b2446460f3db4c2a98b823b627f6cef88d1119f38c46e882bd10c34bb37d47

test:
  secret_key_base: 0510daa40d8777bc9a23f079ea1e3ee888b82ed7fa8e4a0a4283dbbc4774ec05de3e4ea689447f5328b8d225c69f4bfaf803f1ae33ac22802f0aa9d0cd5b5bd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
